server {
    listen 80;
    server_name ii.reverie.dpdns.org;
    root /var/www/html;   # 如果你知道实际 root 路径可以改，不知道就保持这样

    # 只有 ocmusic 重写
    location /crmusic/ocmusic/ {
        rewrite ^/crmusic/ocmusic/v1/music/(.*)$ /crmusic/ocmusic.php?path=$1 last;
    }

    # PHP 处理
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass unix:/var/run/php/php8.x-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # 兜底
    location / {
        try_files $uri $uri/ /web/index.html;
    }
}